plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'com.modrinth.minotaur'
}

modrinth {
    token = System.getenv('MODRINTH_TOKEN')
    projectId = 'ZDK6mUGM'
    versionName = "[${minecraft_version}] B2B (${version}, Fabric)"
    versionNumber = "${version}"
    versionType = 'release'
    uploadFile = remapJar
    changelog = rootProject.file('CHANGELOG.txt').text
    gameVersions = ["1.21", "1.21.1"]
    loaders = ['fabric']

    dependencies {
        required.project "P7dR8mSH"
        required.project "codAaoxh"
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "maven.modrinth:midnightlib:${midnightlib_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
